
version: "3.4"
networks:
  proxynetwork:
    external: true
  net:
    driver: overlay
    attachable: true
services:
  back:
    image: koromerzhin/nodejs:15.1.0-express
    volumes:
      - ${PWD}/back:/app
    networks:
      - proxynetwork
      - net
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.back-streamchat.rule=Host(`back-streamchat.traefik.me`)"
        - "traefik.http.routers.back-streamchat-tls.tls.domains[0].main=back-streamchat.traefik.me"
        - "traefik.http.routers.back-streamchat-tls.tls.domains[0].sans=back-streamchat-*.traefik.me"
        - "traefik.http.services.back-streamchat.loadbalancer.server.port=3000"
  front:
    image: koromerzhin/nodejs:1.1.3-quasar
    volumes:
      - ${PWD}/front:/app
    networks:
      - proxynetwork
      - net
    depends_on:
      - back
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.streamchat.rule=Host(`streamchat.traefik.me`)"
        - "traefik.http.routers.streamchat-tls.tls.domains[0].main=streamchat.traefik.me"
        - "traefik.http.routers.streamchat-tls.tls.domains[0].sans=streamchat-*.traefik.me"
        - "traefik.http.services.streamchat.loadbalancer.server.port=80"